#!/usr/bin/ruby

require 'beaneater'
require 'json'
require 'optparse'
require 'yaml'

options = {}
options[:server] ="localhost:11300"
options[:body] = Time.now.to_s

OptionParser.new do |opts|
	opts.banner = "Usage: injecter [options]"
	opts.on('-c', '--connect HOST:PORT', 'beanstalk server to connect to (defaults to localhost:11300)') { |v| options[:server] = v }
	opts.on('-b', '--body STRING', 'use STRING as job body (defaults to current time)') { |v| options[:body] = v }
	opts.on('-d', '--debug', 'spit out debug infos') { |v| options[:debug] = v }
end.parse!

beanpool = Beaneater::Pool.new([options[:server]])

ARGV.each do |tubename|
	beanpool.tubes[tubename].put options[:body]
end

# Disconnect the pool
beanpool.close

